default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quest_development
  username: rails_dev
  password: qwerty123
  host: localhost
  port: 5432

test:
  <<: *default
  database: quest_test
  host: localhost
  port: 5432
  username: rails_dev
  password: qwerty123

production:
  <<: *default
  database: quest_production
  username: quest
  password: <%= ENV['NEWSAPP_DATABASE_PASSWORD'] %>